#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://kadan1:8761/eureka/,http://kadan1:8762/eureka/
#
#spring:
#  zipkin:
#    base-url: http://kadan1:7777
#  sleuth:
#    sampler:
#      percentage: 1.0

