#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://kadan1:8761/eureka/,http://kadan1:8762/eureka/
#
#spring:
#  zipkin:
#    base-url: http://kadan1:7777
#  sleuth:
#    sampler:
#      percentage: 1.0
#jasypt:
#  encryptor:
#    password: demoStudio$$

spring:
#  application:
#    name: lb-service
  cloud:
    config:
      bootstrap:
        enabled: false
      discovery:
        enabled: false
        service-id: lb-service
      label: master
      profile: uat
      uri: http://kadan1:8080/
#      label: ${config_label}
#      profile: ${config_profile}
#      uri: http://${config_host}:${config_port}/
      username: adminTest
      password: admin
server:
  port: 8088